export const homeData = [
  {
    id: 1,
    name: "You",
    time: "4 sezon 10 bölüm",
    desc: "O, həmçinin Marienni tapmaq üçün Avropada izləyir. Serial qatil öz elit qrupunu hədəf almağa başlayanda bir-bir ölməyə başlayan varlı sosialistlər dairəsi ilə əlaqə qurmağa başlayanda onun yeni təklik həyatı pozulur.  ",
    starring: "Brenda Chapman, Jeff Nathanson",
    janr: "Macəra",
    tags: "Dedektiv fantastika, Sirr, Romantika",
    cover: "https://m.media-amazon.com/images/M/MV5BN2YwNTZhNjUtNWJiMC00OTYwLWFkNjEtOWRhNTc4ZDBlOWE0XkEyXkFqcGdeQWFybm8@._V1_.jpg",
    video: "../video/video2.mp4",
    date: "10-JUL-2021",
  },
  {
    
    id: 2,
    name: "The Godfather",
    time: "145 dəqiqə",
    desc: "Vitonun kiçik oğlu Maykl, indiyə qədər ailə işindən kənarda qalan dəniz piyadası, qəbulda sevgilisi Kay Adamsı ailəsi ilə tanış edir. Məşhur müğənni və Vitonun xaç oğlu Conni Fontan filmdə rol almaq üçün Vitodan kömək istəyir.",
    starring: "Vito, Michael Corleone , Mary Corleone",
    janr: "Mafia",
    tags: "Müharibə, Macəra, Şiddət",
    cover: "https://www.filmlinc.org/wp-content/uploads/2011/08/NYFF57_Retrospective_TheGodfatherPartII_02-1.jpg",
    video: "../video/video1.mp4",
    date: "20-Jan-1997",
  },
  {
    id: 3,
    name: "Inception",
    time: "156 dəqiqə",
    desc: "Demək olar ki, hər kəsin indiyə qədər bildiyi kimi, İnception-ın titul konsepsiyası bir ideyanın personajın şüuraltına yerləşdirilməsidir - filmin daha az və ya çox görünməmiş kimi təqdim etdiyi bir anlayış. ",
    starring: "Leonardo DiKaprio,  Cozef Qordon-Levitt",
    janr: "Macəra",
    tags: "Dedektiv,Horror,Action ",
    cover: "https://variety.com/wp-content/uploads/2023/07/MCDINCE_EC027.jpg",
    video: "../video/video3.mp4",
    date: "20-FEB-2010",
  },
  {
    id: 4,
    name: "The Queens Gambit",
    time: "203 dəqiqə",
    desc: "Kraliçanın Qambiti emosional problemlər, narkotik və alkoqol asılılığı ilə mübarizə apararkən elit şahmatçı olmaq axtarışında olan yetim şahmat vunderkindisi Elizabeth Harmonun həyatını izləyir. Seriyanın adı eyni adlı şahmat açılışına aiddir. Hekayə 1950-ci və 1960-cı illərin ortalarına təsadüf edir.",
    starring: "Karen Gilchrist, James Earl Jones",
    janr: "Dedektiv",
    tags: " Qorxu, Macəra, Şiddət",
    cover: "https://images.squarespace-cdn.com/content/v1/57c92580c534a5c7c898f469/1605847077405-DM4FGSEHLH6FLNKZU1ZW/ReviewQueensGambit.jpg",
    video: "../video/video4.mp4",
    date: "12-Aug-2015",
  },
]
export const upcome = [
  {
    id: 1,
    cover: "https://c4.wallpaperflare.com/wallpaper/979/77/278/shrek-cartoon-crown-stroller-wallpaper-preview.jpg",
    name: "Shrek 2",
    time: "172 dəqiqə",
  },
  {
    id: 2,
    cover: "https://news.masha.place/uploads/attachments/2023/09/28/1695848716_Image_1_(1).png",
    name: "Maşa və Ayı",
    time: "45 dəqiqə",
  },
  {
    id: 3,
    cover: "https://www.hollywoodreporter.com/wp-content/uploads/2021/05/the-boss-baby-family-business-BB2_Tsr1Sheet10_RGB_2_rgb-copy.jpg?w=1024",
    name: "Boss Baby",
    time: "121 dəqiqə",
  },
  {
    id: 4,
    cover: "https://www.intofilm.org/intofilm-production/7019/scaledcropped/970x546/resources/7019/kung-fu-panda-2-ep-dreamworks-animation.jpg",
    name: "Kung-Fu Panda",
    time: "215 dəqiqə",
  },
  {
    id: 5,
    cover: "../images/upcome/u5.jpg",
    name: "Jumbo Queen",
    time: "156 dəqiqə",
  },
]
export const latest = [
  {
    id: 1,
    cover: "../images/upcome/u6.png",
    name: "King of Jungle",
    time: "156 dəqiqə",
  },
  {
    id: 2,
    cover: "../images/upcome/u7.jpg",
    name: "The illusion",
    time: "172 dəqiqə",
  },
  {
    id: 3,
    cover: "../images/upcome/u1.jpg",
    name: "Latest Movie",
    time: "134 dəqiqə",
  },
  {
    id: 4,
    cover: "../images/upcome/u5.jpg",
    name: "Latest two",
    time: "121 dəqiqə",
  },
  {
    id: 5,
    cover: "../images/upcome/u4.jpg",
    name: "Latest Three",
    time: "162 dəqiqə",
  },
]

export const trending = [
  {
    id: 1,
    name: "The Dinosaur",
    rating: 4.7,
    time: "142 dəqiqə",
    desc: "O, həmçinin Marienni tapmaq üçün Avropada izləyir. Serial qatil öz elit qrupunu hədəf almağa başlayanda bir-bir ölməyə başlayan varlı sosialistlər dairəsi ilə əlaqə qurmağa başlayanda onun yeni təklik həyatı pozulur. ",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Macəra ",
    tags: "Fantastika ,Əyləncə , Şiddət",
    cover: "../images/img/slide1.png",
    date: "20-Jan-1997",
  },
  {
    id: 2,
    name: "The Great Emperor",
    rating: 4.6,
    time: "175 dəqiqə",
    desc: "Ada, onun sakinləri kimi, tamamilə uydurmadır. Konqun Sakit okeandakı ada evi Konq özü ilə birlikdə ilk dəfə 1933-cü ildə çəkilmiş King Kong filmində görünür.",
    starring: "Brenda Chapman, Jeff Nathanson",
    genres: "Macəra ",
    tags: "Qorxu ,Animasiya ,Ailə",
    cover: "../images/img/slide2.jpg",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "Jumbo Queen",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "Piratçılıq, adətən yük və digər qiymətli əşyaları və ya əmlakı oğurlamaq məqsədi ilə gəmi və ya qayıqla hücum edənlər tərəfindən başqa bir gəmiyə və ya sahilyanı əraziyə quldurluq və ya cinayət xarakterli zorakılıq aktıdır. ",
    starring: "James Chinlund, Jeff Nathanson",
    genres: "Macəra ",
    tags: "Şiddət ,Qorxu ,Həyəcan  ",
    cover: "../images/img/slide3.jpg",
    date: "20-FEB-2010",
  },
]
export const recommended = [
  {
    id: 4,
    cover: "../images/rec/rec1.jpg",
    name: "One Man Army",
    time: "158 dəqiqə",
  },
  {
    id: 5,
    cover: "../images/rec/rec2.jpg",
    name: "Jumbo Queen",
    time: "132 dəqiqə",
  },
  {
    id: 1,
    cover: "../images/rec/rec3.jpg",
    name: "My office Boss",
    time: "123 dəqiqə",
  },
  {
    id: 2,
    cover: "../images/rec/rec4.jpg",
    name: "Shadowe",
    time: "156 dəqiqə",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "Another Danger",
    time: "128 dəqiqə",
  },
]
