export const homeData = [
  {
    id: 1,
    name: "You",
    time: "4 sezon 10 bölüm",
    desc: "O, həmçinin Marienni tapmaq üçün Avropada izləyir. Serial qatil öz elit qrupunu hədəf almağa başlayanda bir-bir ölməyə başlayan varlı sosialistlər dairəsi ilə əlaqə qurmağa başlayanda onun yeni təklik həyatı pozulur.  ",
    starring: "Brenda Chapman, Jeff Nathanson",
    janr: "Macəra",
    tags: "Dedektiv fantastika, Sirr, Romantika",
    cover: "https://m.media-amazon.com/images/M/MV5BN2YwNTZhNjUtNWJiMC00OTYwLWFkNjEtOWRhNTc4ZDBlOWE0XkEyXkFqcGdeQWFybm8@._V1_.jpg",
    video: "../video/video2.mp4",
    date: "10-JUL-2021",
  },
  {
    
    id: 2,
    name: "The Godfather",
    time: "145 dəqiqə",
    desc: "Vitonun kiçik oğlu Maykl, indiyə qədər ailə işindən kənarda qalan dəniz piyadası, qəbulda sevgilisi Kay Adamsı ailəsi ilə tanış edir. Məşhur müğənni və Vitonun xaç oğlu Conni Fontan filmdə rol almaq üçün Vitodan kömək istəyir.",
    starring: "Vito, Michael Corleone , Mary Corleone",
    janr: "Mafia",
    tags: "Müharibə, Macəra, Şiddət",
    cover: "https://www.filmlinc.org/wp-content/uploads/2011/08/NYFF57_Retrospective_TheGodfatherPartII_02-1.jpg",
    video: "../video/video1.mp4",
    date: "20-Jan-1997",
  },
  {
    id: 3,
    name: "Inception",
    time: "156dəqiqə",
    desc: "Demək olar ki, hər kəsin indiyə qədər bildiyi kimi, İnception-ın titul konsepsiyası bir ideyanın personajın şüuraltına yerləşdirilməsidir - filmin daha az və ya çox görünməmiş kimi təqdim etdiyi bir anlayış. ",
    starring: "Leonardo DiKaprio,  Cozef Qordon-Levitt",
    janr: "Macəra",
    tags: "Dedektiv,Horror,Action ",
    cover: "https://variety.com/wp-content/uploads/2023/07/MCDINCE_EC027.jpg",
    video: "../video/video3.mp4",
    date: "20-FEB-2010",
  },
  {
    id: 4,
    name: "The Queens Gambit",
    time: "203 dəqiqə",
    desc: "Kraliçanın Qambiti emosional problemlər, narkotik və alkoqol asılılığı ilə mübarizə apararkən elit şahmatçı olmaq axtarışında olan yetim şahmat vunderkindisi Elizabeth Harmonun həyatını izləyir. Seriyanın adı eyni adlı şahmat açılışına aiddir. Hekayə 1950-ci və 1960-cı illərin ortalarına təsadüf edir.",
    starring: "Karen Gilchrist, James Earl Jones",
    janr: "Dedektiv",
    tags: " Qorxu, Macəra, Şiddət",
    cover: "https://images.squarespace-cdn.com/content/v1/57c92580c534a5c7c898f469/1605847077405-DM4FGSEHLH6FLNKZU1ZW/ReviewQueensGambit.jpg",
    video: "../video/video4.mp4",
    date: "12-Aug-2015",
  },
]
export const upcome = [
  {
    id: 1,
    cover: "../images/upcome/u1.jpg",
    name: "My office Boss",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u2.jpg",
    name: "Shadowe",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "Another Danger",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u4.jpg",
    name: "One Man Army",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u5.jpg",
    name: "Jumbo Queen",
    time: "2hr : 38mins",
  },
]
export const latest = [
  {
    id: 1,
    cover: "../images/upcome/u6.png",
    name: "King of Jungle",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u7.jpg",
    name: "The illusion",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u1.jpg",
    name: "Latest Movie",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u5.jpg",
    name: "Latest two",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u4.jpg",
    name: "Latest Three",
    time: "2hr : 38mins",
  },
]

export const trending = [
  {
    id: 1,
    name: "The Dinosaur",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: "../images/img/slide1.png",
    date: "20-Jan-1997",
  },
  {
    id: 2,
    name: "The Great Emperor",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
    starring: "Brenda Chapman, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Animation,Family",
    cover: "../images/img/slide2.jpg",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "Jumbo Queen",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
    starring: "James Chinlund, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Action ",
    cover: "../images/img/slide3.jpg",
    date: "20-FEB-2010",
  },
]
export const recommended = [
  {
    id: 4,
    cover: "../images/rec/rec1.jpg",
    name: "One Man Army",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/rec/rec2.jpg",
    name: "Jumbo Queen",
    time: "2hr : 38mins",
  },
  {
    id: 1,
    cover: "../images/rec/rec3.jpg",
    name: "My office Boss",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/rec/rec4.jpg",
    name: "Shadowe",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "Another Danger",
    time: "2hr : 38mins",
  },
]
